Добавление локализаций
luisakisa/RN_test pull request #16
Opened 2023-05-12 10:50 UTC by luisakisa

**Задача**
#14
**Описание**
Добавление локализаций(использование библиотеки react-i18next)

2023-05-14 11:08 UTC, ZloyRob requested changes

2023-05-14 11:08 UTC, ZloyRob commented on components/RadioButtonsGroup/index.tsx
> +  ];
Это можно сделать и не заводя все в функцию, а просто импортить i18n сразу из пакета, а не хука.

2023-05-14 11:08 UTC, ZloyRob commented on components/StyledTextInput/index.tsx
> +        placeholder={textPlaceholder}
зачем тут выносить перевод в константу и почему не использовать сразу `t`?

2023-05-14 11:08 UTC, ZloyRob commented on package.json
> +    "i18next-http-backend": "^2.2.0",
??

2023-05-14 11:08 UTC, ZloyRob commented on App.tsx
> +import './i18n';
Почему это тут?

2023-05-15 09:31 UTC, luisakisa commented on App.tsx
> +import './i18n';
А есть разница между импортом в app и в index?

2023-05-15 09:33 UTC, ZloyRob commented on App.tsx
> +import './i18n';
иногда бывает, в данном случае ну должно быть разницы, просто спросил)

2023-05-15 09:47 UTC, luisakisa commented on components/StyledTextInput/index.tsx
> +        placeholder={textPlaceholder}
потому что возникает ошибка из-за типизации, но, видимо, можно сделать так placeholder={t("third.placeholder") as string}

2023-05-15 09:48 UTC, luisakisa commented on package.json
> +    "i18next-http-backend": "^2.2.0",
ну тут да, это уже не используется

2023-05-15 10:08 UTC, ZloyRob commented on components/RadioButtonsGroup/index.tsx
> +('./../../i18n');
а это кто?)

2023-05-15 10:08 UTC, ZloyRob commented on components/RadioButtonsGroup/index.tsx
>        days: 7,
А теперь раз ты так сделала, можно data вернуть на ее место, перед функцией. Есть вероятность что в таком контексте переводы не успеют загрузиться во время сборки. Если так случится, то data можно будет переделать в функцию.

2023-05-15 10:13 UTC, luisakisa commented on components/RadioButtonsGroup/index.tsx
> +('./../../i18n');
🤡

2023-05-15 10:15 UTC, luisakisa commented on components/RadioButtonsGroup/index.tsx
>        days: 7,
а, так вот зачем оно все было

2023-05-15 10:23 UTC, ZloyRob commented on components/RadioButtonsGroup/index.tsx
>        days: 7,
обычно подобная дата лежит вообще в отдельных файлах, тк занимает 100+ строк и хранить ее в компоненте или экране будет неудобно;

2023-05-15 10:27 UTC, ZloyRob commented on components/RadioButtonsGroup/index.tsx
> +  },
Попробуй переустановить и перезапустить приложение, нужно проверить во всех ли кейсах переводы работают.

2023-05-15 10:28 UTC, luisakisa commented on components/RadioButtonsGroup/index.tsx
> +  },
press f

2023-05-15 10:32 UTC, ZloyRob commented on components/RadioButtonsGroup/index.tsx
> +  },
тогда переделывай константу в функцию
```ts
const data = () => {
    return ([{}, {} ....])
}
```
 А где ее используешь в коде просто сначала вызывай `data().map ....`

2023-05-15 10:44 UTC, ZloyRob approved these changes

2023-05-15 10:45 UTC, merged